# Site settings
title: Tailored Tunes  
subHeading:  Article Of The Day
email: hello@tailored-tunes.com
description: > # Article Of The Day is a collection of daily article recommendations from the Tailored Tunes team.
  We use it to keep our interest and view of the world up to date.
url: "http://aotd.tailored-tunes.com" # the base hostname & protocol for your site
twitter_username: tailored_tunes
github_username:  tailored-tunes
permalink: /:year-:month-:day-:title.html
baseurl:
# Build settings
markdown: kramdown
exclude: [vendor]
paginate: 7
